### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by YunusMG** [grg2rsr/ILTIS#27]
(ILTIS) Yunusas-MacBook-Air:ILTIS_master_2 yunusa$ pip install ./
Processing /Users/yunusa/Documents/ILTIS_master_2
    ERROR: Command errored out with exit status 1:
     command: /Users/yunusa/anaconda3/envs/ILTIS/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/setup.py'"'"'; __file__='"'"'/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/pip-egg-info
         cwd: /private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/setup.py", line 21, in <module>
        setup(**config)
      File "/Users/yunusa/anaconda3/envs/ILTIS/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/yunusa/anaconda3/envs/ILTIS/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/yunusa/anaconda3/envs/ILTIS/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/Users/yunusa/anaconda3/envs/ILTIS/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/Users/yunusa/anaconda3/envs/ILTIS/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/Users/yunusa/anaconda3/envs/ILTIS/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/.eggs/setuptools_scm-3.3.3-py3.7.egg/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/.eggs/setuptools_scm-3.3.3-py3.7.egg/setuptools_scm/__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd/.eggs/setuptools_scm-3.3.3-py3.7.egg/setuptools_scm/__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/private/var/folders/vy/smlwmtbn5mgb_8gvx_jpns500000gn/T/pip-req-build-z6ukxymd'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ajkswamy** [comment]
@YunusMG Sorry for the late response. The above error is usually caused when you download the repository as a ZIP file, extract it and try to install from it. Could you try to clone it (`git clone https://github.com/ajkswamy/ILTIS.git`), navigate into the cloned directory and try `pip install .` again?
P.S.: If you do not already have, you might have to install `git` onto your system.
